let wrong=JSON.parse(localStorage.getItem('p6wrong')||'[]');
let history=JSON.parse(localStorage.getItem('p6history')||'[]');
const $=id=>document.getElementById(id);
function norm(s){return(s||'').toLowerCase().replace(/[.,!?;:()[\]"']/g,' ').replace(/\s+/g,' ').trim()}
function show(id){['mark','book','stats'].forEach(x=>$(x).classList.add('hidden'));$(id).classList.remove('hidden');render()}
function mark(){let q=$('q').value.trim(),c=$('correct').value.trim(),s=$('student').value.trim(),type=$('type').value,theme=$('theme').value,ks=$('keywords').value.split(',').map(x=>norm(x)).filter(Boolean),marks=+$('marks').value||1;if(!q||!c||!s)return alert('Please enter question, correct answer and student answer.');let ok,reason;if(type==='mcq'){ok=norm(c)===norm(s);reason=ok?'Exact match.':'The answer does not match the correct answer.'}else{let words=ks.length?ks:c.split(/\s+/).filter(x=>x.length>4);let found=words.filter(x=>norm(s).includes(norm(x))).length;ok=found>0;reason=found+'/'+words.length+' key concept(s) detected.'}history.push(ok);localStorage.setItem('p6history',JSON.stringify(history));let item={id:Date.now(),q,c,s,type,theme,marks,reason,date:new Date().toLocaleString()};if(!ok){wrong.unshift(item);localStorage.setItem('p6wrong',JSON.stringify(wrong))}$('result').className='result '+(ok?'ok':'bad');$('result').innerHTML='<b>'+(ok?'✅ Correct':'❌ Needs Review')+'</b><br>'+reason+(ok?'':'<br><br><b>Focus:</b> Review the scientific concept and required keywords.');render()}
function render(){$('list').innerHTML=wrong.length?wrong.map(x=>'<div class="item"><b>'+esc(x.q)+'</b><br><small>'+x.theme+' • '+x.type+' • '+x.date+'</small><p><b>Student:</b> '+esc(x.s)+'</p><p><b>Correct:</b> '+esc(x.c)+'</p><p><b>Feedback:</b> '+esc(x.reason)+'</p><button class="button secondary" onclick="removeWrong('+x.id+')">Remove</button></div>').join(''):'<p>No wrong answers yet 🎉</p>';$('total').textContent=history.length;$('wrong').textContent=wrong.length;$('accuracy').textContent=history.length?Math.round(history.filter(Boolean).length/history.length*100)+'%':'0%';$('themes').innerHTML=['Diversity','Cycles','Systems','Interactions','Energy'].map(t=>'<p><b>'+t+'</b>: '+wrong.filter(x=>x.theme===t).length+' wrong</p>').join('')}
function removeWrong(id){wrong=wrong.filter(x=>x.id!==id);localStorage.setItem('p6wrong',JSON.stringify(wrong));render()}
function clearWrong(){if(confirm('Clear all wrong answers?')){wrong=[];localStorage.removeItem('p6wrong');render()}}
function demo(){$('q').value='Why does water level in an open container decrease after several hours?';$('type').value='short';$('theme').value='Cycles';$('correct').value='Water evaporates into the air as water vapour.';$('student').value='The water evaporates.';$('keywords').value='evaporates, evaporation';$('marks').value=1}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
render();