const EconomyEngine={
 clamp(v,min=0,max=100){return Math.max(min,Math.min(max,v))},
 init(w){if(w.economy)return w;const l=w.life||{};w.economy={gdp:Math.round(20+w.energy*0.8+(l.technology||40)*0.6),growth:2,production:Math.round(w.energy*1.2),consumption:Math.round((l.population||60)*0.45),trade_balance:0,inflation:2.1,currency:"URC",reserves:Math.round(w.energy*1.5),exports:0,imports:0};return w},
 tick(w){this.init(w);const e=w.economy,l=w.life||{};const demand=(l.population||60)*.035;const production=Math.max(1,w.energy*.55+(l.technology||40)*.18);const consumption=Math.max(1,demand+w.gate*.05);e.production=Math.round(production);e.consumption=Math.round(consumption);e.growth=Number((1.2+w.ai*.025+w.gate*.012+(production>consumption?.8:-1.1)).toFixed(2));e.gdp=Math.max(1,Math.round(e.gdp*(1+e.growth/100)));e.inflation=Number(this.clamp(e.inflation+(consumption>production?.12:-.08),0,20).toFixed(2));e.exports=Math.round(production*.8);e.imports=Math.round(Math.max(0,consumption-production)*.9);e.trade_balance=e.exports-e.imports;e.reserves=Math.max(0,Math.round(e.reserves+e.trade_balance*.08));return w},
power(w){this.init(w);const e=w.economy;return Math.round(e.gdp*.35+w.energy*.8+w.ai*.5+w.gate*.4)}
};
const DiplomacyEngine={
 init(w){if(w.politics)return w;w.politics={sovereignty:100,stability:Math.round(w.life?.stability||70),diplomatic_power:Math.round(30+w.ai*.45+w.gate*.25),government:w.life?.government||"Emerging Council"};w.diplomacy={relations:{},alliances:[],treaties:[],conflicts:{}};return w},
 tick(w,worlds){this.init(w);w.politics.government=w.life?.government||w.politics.government;w.politics.stability=Math.round(Math.max(0,Math.min(100,(w.life?.stability||70)+w.gate*.03-w.economy.inflation*1.2)));for(const o of worlds){if(o.id===w.id)continue;const d=Math.abs(w.energy-o.energy)+Math.abs(w.ai-o.ai)+Math.abs(w.finance-o.finance);let rel=Math.max(-100,Math.min(100,Math.round(100-d/3)));w.diplomacy.relations[o.id]=rel;w.diplomacy.conflicts[o.id]=Math.max(0,Math.round(50-rel/2));if(rel>=65&&!w.diplomacy.alliances.includes(o.id))w.diplomacy.alliances.push(o.id);if(rel>=40&&!w.diplomacy.treaties.includes(o.id))w.diplomacy.treaties.push(o.id)}return w}
};
const MarketEngine={tick(worlds){const total=worlds.reduce((s,w)=>s+EconomyEngine.power(w),0)||1;const avg=worlds.reduce((s,w)=>s+w.economy.gdp,0)/worlds.length;return{mwi:Math.round(total/worlds.length),energy_price:Number((1.2+worlds.reduce((s,w)=>s+w.economy.consumption-w.economy.production,0)/Math.max(1,worlds.length)*.01).toFixed(2)),urc_rate:Number((1+avg/1000).toFixed(3)),world_gdp:Math.round(avg*worlds.length)}}};
